apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-monitor
  labels:
    app: mall-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-monitor
  template:
    metadata:
      labels:
        app: mall-monitor
    spec:
      containers:
        - name: mall-monitor
          # 指定Docker Hub中的镜像地址
          image: macrodocker/mall-monitor:1.0-SNAPSHOT
          ports:
            - containerPort: 8101
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVERADDR
              value: http://nacos:8849
            - name: SPRING_CLOUD_NACOS_CONFIG_SERVERADDR
              value: http://nacos:8849
            - name: spring_datasource_url
              value: jdbc:mysql://mall-mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            - name: spring_elasticsearch_rest_uris
              value: elasticsearch:9200
            - name: spring_redis_host
              value: redis
            - name: spring_rabbitmq_host
              value: rabbitmq
            - name: spring_rabbitmq_username
              value: guest
            - name: spring_rabbitmq_password
              value: guest
          volumeMounts:
            - mountPath: /var/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mydata/app/mall-monitor/logs
            type: DirectoryOrCreate