apiVersion: v1
kind: Service
metadata:
  name: mall-admin
  labels:
    app: mall-admin
spec:
  type: ClusterIP
  selector:
    app: mall-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080